var raw_data = [
        {
            "info": null,
            "leaf": false,
            "name": "ZARZĄDZANIE PAŃSTWEM",
            "parent": null,
            "v_eu": 25140,
            "idef": "1",
            "level": "a",
            "v_proc_nation": 98.39,
            "v_total": 1561521,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 1536381,
            "v_proc_eu": 1.61,
            "type": "FUNKCJA 1"
        },
        {
            "info": null,
            "leaf": false,
            "name": "BEZPIECZEŃSTWO WEWNĘTRZNE I PORZĄDEK PUBLICZNY",
            "parent": null,
            "v_eu": 58779,
            "idef": "2",
            "level": "a",
            "v_proc_nation": 99.59,
            "v_total": 14170616,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 14111837,
            "v_proc_eu": 0.41,
            "type": "FUNKCJA 2"
        },
        {
            "info": null,
            "leaf": false,
            "name": "EDUKACJA, WYCHOWANIE I OPIEKA",
            "parent": null,
            "v_eu": 1016384,
            "idef": "3",
            "level": "a",
            "v_proc_nation": 92.93,
            "v_total": 14379196,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 13362812,
            "v_proc_eu": 7.07,
            "type": "FUNKCJA 3"
        },
        {
            "info": null,
            "leaf": false,
            "name": "ZARZĄDZANIE FINANSAMI PAŃSTWA",
            "parent": null,
            "v_eu": 36781689,
            "idef": "4",
            "level": "a",
            "v_proc_nation": 77.39,
            "v_total": 162662835,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 125881146,
            "v_proc_eu": 22.61,
            "type": "FUNKCJA 4"
        },
        {
            "info": null,
            "leaf": false,
            "name": "OCHRONA PRAW I INTERESÓW SKARBU PAŃSTWA",
            "parent": null,
            "v_eu": 0,
            "idef": "5",
            "level": "a",
            "v_proc_nation": 100.0,
            "v_total": 199435,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 199435,
            "v_proc_eu": 0.0,
            "type": "FUNKCJA 5"
        },
        {
            "info": null,
            "leaf": false,
            "name": "POLITYKA GOSPODARCZA KRAJU",
            "parent": null,
            "v_eu": 1643467,
            "idef": "6",
            "level": "a",
            "v_proc_nation": 61.95,
            "v_total": 4319308,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 2675841,
            "v_proc_eu": 38.05,
            "type": "FUNKCJA 6"
        },
        {
            "info": null,
            "leaf": false,
            "name": "GOSPODARKA PRZESTRZENNA, BUDOWNICTWO I MIESZKALNICTWO",
            "parent": null,
            "v_eu": 63034,
            "idef": "7",
            "level": "a",
            "v_proc_nation": 96.33,
            "v_total": 1716568,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 1653534,
            "v_proc_eu": 3.67,
            "type": "FUNKCJA 7"
        },
        {
            "info": null,
            "leaf": false,
            "name": "KULTURA FIZYCZNA I SPORT",
            "parent": null,
            "v_eu": 0,
            "idef": "8",
            "level": "a",
            "v_proc_nation": 100.0,
            "v_total": 1092963,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 1092963,
            "v_proc_eu": 0.0,
            "type": "FUNKCJA 8"
        },
        {
            "info": null,
            "leaf": false,
            "name": "KULTURA I DZIEDZICTWO NARODOWE",
            "parent": null,
            "v_eu": 0,
            "idef": "9",
            "level": "a",
            "v_proc_nation": 100.0,
            "v_total": 1317359,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 1317359,
            "v_proc_eu": 0.0,
            "type": "FUNKCJA 9"
        },
        {
            "info": null,
            "leaf": false,
            "name": "NAUKA POLSKA",
            "parent": null,
            "v_eu": 760643,
            "idef": "10",
            "level": "a",
            "v_proc_nation": 86.1,
            "v_total": 5471569,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 4710926,
            "v_proc_eu": 13.9,
            "type": "FUNKCJA 10"
        },
        {
            "info": null,
            "leaf": false,
            "name": "BEZPIECZEŃSTWO ZEWNĘTRZNE I NIENARUSZALNOŚĆ GRANIC",
            "parent": null,
            "v_eu": 0,
            "idef": "11",
            "level": "a",
            "v_proc_nation": 100.0,
            "v_total": 20885383,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 20885383,
            "v_proc_eu": 0.0,
            "type": "FUNKCJA 11"
        },
        {
            "info": null,
            "leaf": false,
            "name": "ŚRODOWISKO",
            "parent": null,
            "v_eu": 3034025,
            "idef": "12",
            "level": "a",
            "v_proc_nation": 21.77,
            "v_total": 3878397,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 844372,
            "v_proc_eu": 78.23,
            "type": "FUNKCJA 12"
        },
        {
            "info": null,
            "leaf": false,
            "name": "ZABEZPIECZENIE SPOŁECZNE I WSPIERANIE RODZINY",
            "parent": null,
            "v_eu": 3996,
            "idef": "13",
            "level": "a",
            "v_proc_nation": 100.0,
            "v_total": 85035429,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 85031433,
            "v_proc_eu": 0.0,
            "type": "FUNKCJA 13"
        },
        {
            "info": null,
            "leaf": false,
            "name": "RYNEK PRACY",
            "parent": null,
            "v_eu": 376843,
            "idef": "14",
            "level": "a",
            "v_proc_nation": 73.25,
            "v_total": 1408910,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 1032067,
            "v_proc_eu": 26.75,
            "type": "FUNKCJA 14"
        },
        {
            "info": null,
            "leaf": false,
            "name": "POLITYKA ZAGRANICZNA",
            "parent": null,
            "v_eu": 3230,
            "idef": "15",
            "level": "a",
            "v_proc_nation": 99.82,
            "v_total": 1830501,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 1827271,
            "v_proc_eu": 0.18,
            "type": "FUNKCJA 15"
        },
        {
            "info": null,
            "leaf": false,
            "name": "SPRAWY OBYWATELSKIE",
            "parent": null,
            "v_eu": 293988,
            "idef": "16",
            "level": "a",
            "v_proc_nation": 81.02,
            "v_total": 1548673,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 1254685,
            "v_proc_eu": 18.98,
            "type": "FUNKCJA 16"
        },
        {
            "info": null,
            "leaf": false,
            "name": "RÓWNOMIERNY ROZWÓJ KRAJU",
            "parent": null,
            "v_eu": 12822042,
            "idef": "17",
            "level": "a",
            "v_proc_nation": 16.21,
            "v_total": 15303315,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 2481273,
            "v_proc_eu": 83.79,
            "type": "FUNKCJA 17"
        },
        {
            "info": null,
            "leaf": false,
            "name": "SPRAWIEDLIWOŚĆ",
            "parent": null,
            "v_eu": 35727,
            "idef": "18",
            "level": "a",
            "v_proc_nation": 99.6,
            "v_total": 8856432,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 8820705,
            "v_proc_eu": 0.4,
            "type": "FUNKCJA 18"
        },
        {
            "info": null,
            "leaf": false,
            "name": "INFRASTRUKTURA TRANSPORTOWA",
            "parent": null,
            "v_eu": 7719549,
            "idef": "19",
            "level": "a",
            "v_proc_nation": 47.32,
            "v_total": 14654234,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 6934685,
            "v_proc_eu": 52.68,
            "type": "FUNKCJA 19"
        },
        {
            "info": null,
            "leaf": false,
            "name": "ZDROWIE",
            "parent": null,
            "v_eu": 404917,
            "idef": "20",
            "level": "a",
            "v_proc_nation": 95.41,
            "v_total": 8813577,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 8408660,
            "v_proc_eu": 4.59,
            "type": "FUNKCJA 20"
        },
        {
            "info": null,
            "leaf": false,
            "name": "POLITYKA ROLNA I RYBACKA",
            "parent": null,
            "v_eu": 18939562,
            "idef": "21",
            "level": "a",
            "v_proc_nation": 22.8,
            "v_total": 24532926,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 5593364,
            "v_proc_eu": 77.2,
            "type": "FUNKCJA 21"
        },
        {
            "info": null,
            "leaf": false,
            "name": "PLANOWANIE STRATEGICZNE ORAZ OBSŁUGA ADMINISTRACYJNA I TECHNICZNA",
            "parent": null,
            "v_eu": 21031,
            "idef": "22",
            "level": "a",
            "v_proc_nation": 99.46,
            "v_total": 3865561,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 3844530,
            "v_proc_eu": 0.54,
            "type": "FUNKCJA 22"
        },
        {
            "info": null,
            "leaf": false,
            "name": "Koordynacja merytoryczna działalności, planowania strategicznego i operacyjnego",
            "parent": "22",
            "v_eu": 45,
            "idef": "22-1",
            "level": "b",
            "v_proc_nation": 99.99,
            "v_total": 700665,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 700620,
            "v_proc_eu": 0.01,
            "type": "Zadanie 22.1"
        },
        {
            "info": null,
            "leaf": false,
            "name": "Obsługa administracyjna",
            "parent": "22",
            "v_eu": 20347,
            "idef": "22-2",
            "level": "b",
            "v_proc_nation": 99.16,
            "v_total": 2428264,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 2407917,
            "v_proc_eu": 0.84,
            "type": "Zadanie 22.2"
        },
        {
            "info": null,
            "leaf": false,
            "name": "Obsługa techniczna",
            "parent": "22",
            "v_eu": 639,
            "idef": "22-3",
            "level": "b",
            "v_proc_nation": 99.91,
            "v_total": 736632,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 735993,
            "v_proc_eu": 0.09,
            "type": "Zadanie 22.3"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-1",
                    "parent_sort": "022-002-001",
                    "idef": "22-2-1-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-001-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "< 3,5 %",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-1-1",
                    "parent_sort": "022-002-001-001",
                    "idef": "22-2-1-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-001-001-001",
                    "elem_name": "Wskaźnik poziomu kosztów obsługi administracyjnej",
                    "wartosc_bazowa": "3,4 %"
                }
            ],
            "leaf": true,
            "name": "Kancelaria Senatu",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-1",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 5653,
            "czesc": "03",
            "czesc_name": null,
            "v_nation": 5653,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-2",
                    "parent_sort": "022-002-002",
                    "idef": "22-2-2-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-002-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania KRRiT i Biura KRRiT w zakresie obsługi administracyjnej",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "6,4%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-2-1",
                    "parent_sort": "022-002-002-001",
                    "idef": "22-2-2-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-002-001-001",
                    "elem_name": "Relacja  liczby etatów obsługi administracyjnej do liczby etatów ogółem",
                    "wartosc_bazowa": "6,1%"
                }
            ],
            "leaf": true,
            "name": "Krajowa Rada Radiofonii i Telewizji",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-2",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 2746,
            "czesc": "09",
            "czesc_name": null,
            "v_nation": 2746,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-3",
                    "parent_sort": "022-002-003",
                    "idef": "22-2-3-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-003-001",
                    "elem_name": "Zapewnienie sprawnej i efektywnej obsługi organów wyborczych",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "67,0",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-3-1",
                    "parent_sort": "022-002-003-001",
                    "idef": "22-2-3-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-003-001-001",
                    "elem_name": "Odsetek osób oceniających pozytywnie obsługę administracyjną jednostki (średnia ocen powyżej 3 w skali 1-5), na podstawie ankiet",
                    "wartosc_bazowa": "-"
                }
            ],
            "leaf": true,
            "name": "Krajowe Biuro Wyborcze",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-3",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 35487,
            "czesc": "11",
            "czesc_name": null,
            "v_nation": 35487,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-4",
                    "parent_sort": "022-002-004",
                    "idef": "22-2-4-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-004-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "pozytywna",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-4-1",
                    "parent_sort": "022-002-004-001",
                    "idef": "22-2-4-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-004-001-001",
                    "elem_name": "Ocena efektywności obsługi administracyjnej PIP",
                    "wartosc_bazowa": "pozytywna"
                }
            ],
            "leaf": true,
            "name": "Państwowa Inspekcja Pracy",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-4",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 44644,
            "czesc": "12",
            "czesc_name": null,
            "v_nation": 44644,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-5",
                    "parent_sort": "022-002-005",
                    "idef": "22-2-5-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-005-001",
                    "elem_name": "Zapewnienie sprawnej obsługi i realizacji zadań Kancelarii Prezesa Rady Ministrów",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": ">=4,3",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-5-1",
                    "parent_sort": "022-002-005-001",
                    "idef": "22-2-5-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-005-001-001",
                    "elem_name": "Stopień zadowolenia pracowników KPRM z obsługi KPRM, na podstawie ankiety",
                    "wartosc_bazowa": "4,3"
                }
            ],
            "leaf": true,
            "name": "Kancelaria Prezesa Rady Ministrów",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-5",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 24427,
            "czesc": "16",
            "czesc_name": null,
            "v_nation": 24427,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-6",
                    "parent_sort": "022-002-006",
                    "idef": "22-2-6-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-006-001",
                    "elem_name": "Zapewnianie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "pozytywny wynik audytu wewnętrznego",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-6-1",
                    "parent_sort": "022-002-006-001",
                    "idef": "22-2-6-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-006-001-001",
                    "elem_name": "Ocena efektywności realizacji zadań administracyjnych Ministerstwa SWiA",
                    "wartosc_bazowa": "pozytywny wynik audytu wewnętrznego"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Spraw Wewnętrznych i Administracji",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-6",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 2704,
            "czesc": "17",
            "czesc_name": null,
            "v_nation": 2704,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-7",
                    "parent_sort": "022-002-007",
                    "idef": "22-2-7-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-007-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "23%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-7-1",
                    "parent_sort": "022-002-007-001",
                    "idef": "22-2-7-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-007-001-001",
                    "elem_name": "Udział pracowników obsługi administracyjnej do ogółu zatrudnionych",
                    "wartosc_bazowa": "23%"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Infrastruktury",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-7",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 9264,
            "czesc": "18",
            "czesc_name": null,
            "v_nation": 9264,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-8",
                    "parent_sort": "022-002-008",
                    "idef": "22-2-8-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-008-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "10,52",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-8-1",
                    "parent_sort": "022-002-008-001",
                    "idef": "22-2-8-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-008-001-001",
                    "elem_name": "Liczba pracowników obsługi administracyjnej na 100 pracowników merytorycznych (%)",
                    "wartosc_bazowa": "10,28"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Finansów",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-8",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 123489,
            "czesc": "19",
            "czesc_name": null,
            "v_nation": 123489,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-9",
                    "parent_sort": "022-002-009",
                    "idef": "22-2-9-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-009-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania Ministerstwa",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "100%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-9-1",
                    "parent_sort": "022-002-009-001",
                    "idef": "22-2-9-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-009-001-001",
                    "elem_name": "Realizacja zadań w danym roku budżetowym",
                    "wartosc_bazowa": "100%"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Gospodarki",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-9",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 57033,
            "czesc": "20",
            "czesc_name": null,
            "v_nation": 57033,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-10",
                    "parent_sort": "022-002-010",
                    "idef": "22-2-10-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-010-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "23%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-10-1",
                    "parent_sort": "022-002-010-001",
                    "idef": "22-2-10-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-010-001-001",
                    "elem_name": "Udział pracowników obsługi administracyjnej do ogółu zatrudnionych (w %)",
                    "wartosc_bazowa": "23%"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Infrastruktury",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-10",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 2810,
            "czesc": "21",
            "czesc_name": null,
            "v_nation": 2810,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-11",
                    "parent_sort": "022-002-011",
                    "idef": "22-2-11-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-011-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "TAK",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-11-1",
                    "parent_sort": "022-002-011-001",
                    "idef": "22-2-11-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-011-001-001",
                    "elem_name": "Wartość logiczna TAK/NIE",
                    "wartosc_bazowa": "TAK"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Środowiska",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-11",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 58011,
            "czesc": "22",
            "czesc_name": null,
            "v_nation": 58011,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-12",
                    "parent_sort": "022-002-012",
                    "idef": "22-2-12-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-012-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu / jednostki i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "Pozytywna",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-12-1",
                    "parent_sort": "022-002-012-001",
                    "idef": "22-2-12-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-012-001-001",
                    "elem_name": "Ocena NIK",
                    "wartosc_bazowa": "Pozytywna"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Kultury i Dziedzictwa Narodowego",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-12",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 17813,
            "czesc": "24",
            "czesc_name": null,
            "v_nation": 17813,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-13",
                    "parent_sort": "022-002-013",
                    "idef": "22-2-13-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-013-001",
                    "elem_name": "Coroczne utrzymanie sprawnego funkcjonowania MSiT i sprawnej obsługi pracowników MSiT",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "35",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-13-1",
                    "parent_sort": "022-002-013-001",
                    "idef": "22-2-13-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-013-001-001",
                    "elem_name": "Liczba niesprawności w funkcjonowaniu MSiT i obsłudze pracowników MSiT w danym roku (w szt.)",
                    "wartosc_bazowa": "40"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Sportu i Turystyki",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-13",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 3704,
            "czesc": "25",
            "czesc_name": null,
            "v_nation": 3704,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-14",
                    "parent_sort": "022-002-014",
                    "idef": "22-2-14-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-014-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "23 %",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-14-1",
                    "parent_sort": "022-002-014-001",
                    "idef": "22-2-14-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-014-001-001",
                    "elem_name": "Udział pracowników obsługi administracyjnej do ogółu zatrudnionych w %",
                    "wartosc_bazowa": "23 %"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Infrastruktury",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-14",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 4478,
            "czesc": "26",
            "czesc_name": null,
            "v_nation": 4478,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-15",
                    "parent_sort": "022-002-015",
                    "idef": "22-2-15-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-015-001",
                    "elem_name": "Zapewnianie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "pozytywny wynik audytu wewnętrznego",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-15-1",
                    "parent_sort": "022-002-015-001",
                    "idef": "22-2-15-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-015-001-001",
                    "elem_name": "Ocena efektywności realizacji zadań administracyjnych Ministerstwa SWiA",
                    "wartosc_bazowa": "pozytywny wynik audytu wewnętrznego"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Spraw Wewnętrznych i Administracji",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-15",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 884,
            "czesc": "27",
            "czesc_name": null,
            "v_nation": 884,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-16",
                    "parent_sort": "022-002-016",
                    "idef": "22-2-16-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-016-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "15%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-16-1",
                    "parent_sort": "022-002-016-001",
                    "idef": "22-2-16-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-016-001-001",
                    "elem_name": "Wskaźnik fluktuacji kadr",
                    "wartosc_bazowa": "12,5%"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Nauki i Szkolnictwa Wyższego",
            "parent": "22-2",
            "v_eu": 1654,
            "idef": "22-2-16",
            "level": "c",
            "v_proc_nation": 96.59,
            "v_total": 48459,
            "czesc": "28",
            "czesc_name": null,
            "v_nation": 46805,
            "v_proc_eu": 3.41,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-17",
                    "parent_sort": "022-002-017",
                    "idef": "22-2-17-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-017-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "-",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-17-1",
                    "parent_sort": "022-002-017-001",
                    "idef": "22-2-17-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-017-001-001",
                    "elem_name": "Opis stopnia osiągnięcia celu",
                    "wartosc_bazowa": "-"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Obrony Narodowej",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-17",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 36073,
            "czesc": "29",
            "czesc_name": null,
            "v_nation": 36073,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-18",
                    "parent_sort": "022-002-018",
                    "idef": "22-2-18-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-018-001",
                    "elem_name": "Zapewnianie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "70%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-18-1",
                    "parent_sort": "022-002-018-001",
                    "idef": "22-2-18-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-018-001-001",
                    "elem_name": "Analiza poziomu satysfakcji  z realizacji celu,  rozumianego jako odsetek osób oceniających pozytywnie obsługę administracyjną urzędu (średnia ocen powyżej 3) w stosunku do liczby osób oceniających, dokonywana w oparciu o ankietę skierowaną do dyrektorów",
                    "wartosc_bazowa": "-"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Edukacji Narodowej",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-18",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 5397,
            "czesc": "30",
            "czesc_name": null,
            "v_nation": 5397,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-19",
                    "parent_sort": "022-002-019",
                    "idef": "22-2-19-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-019-001",
                    "elem_name": "Zapewnianie sprawnego funkcjonowania Urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "-",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-19-1",
                    "parent_sort": "022-002-019-001",
                    "idef": "22-2-19-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-019-001-001",
                    "elem_name": "Wartość środków finansowych przeznaczonych na realizację zadania",
                    "wartosc_bazowa": "-"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Pracy i Polityki Społecznej",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-19",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 8961,
            "czesc": "31",
            "czesc_name": null,
            "v_nation": 8961,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-20",
                    "parent_sort": "022-002-020",
                    "idef": "22-2-20-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-020-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "15,43%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-20-1",
                    "parent_sort": "022-002-020-001",
                    "idef": "22-2-20-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-020-001-001",
                    "elem_name": "Odsetek urzędników służby cywilnej w korpusie służby cywilnej",
                    "wartosc_bazowa": "11,70%"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Rolnictwa i Rozwoju Wsi",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-20",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 14475,
            "czesc": "32",
            "czesc_name": null,
            "v_nation": 14475,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-21",
                    "parent_sort": "022-002-021",
                    "idef": "22-2-21-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-021-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu Ministra RiRW, ARiMR oraz CDR",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "100",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-21-1",
                    "parent_sort": "022-002-021-001",
                    "idef": "22-2-21-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-021-001-001",
                    "elem_name": "Procent udzielonych odpowiedzi na pisma wymagające stanowiska",
                    "wartosc_bazowa": "100"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Rolnictwa i Rozwoju Wsi",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-21",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 1345834,
            "czesc": "33",
            "czesc_name": null,
            "v_nation": 1345834,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-22",
                    "parent_sort": "022-002-022",
                    "idef": "22-2-22-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-022-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "0,19",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-22-1",
                    "parent_sort": "022-002-022-001",
                    "idef": "22-2-22-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-022-001-001",
                    "elem_name": "Udział zatrudnienia w BA, DI, BDG, BZL w zatrudnieniu ogółem w MRR (średniorocznie, liczba etatów)",
                    "wartosc_bazowa": "0,19"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Rozwoju Regionalnego",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-22",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 22636,
            "czesc": "34",
            "czesc_name": null,
            "v_nation": 22636,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-23",
                    "parent_sort": "022-002-023",
                    "idef": "22-2-23-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-023-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "10,81%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-23-1",
                    "parent_sort": "022-002-023-001",
                    "idef": "22-2-23-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-023-001-001",
                    "elem_name": "Odsetek urzędników służby cywilnej w korpusie służby cywilnej w urzędzie",
                    "wartosc_bazowa": "10,90%"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Rolnictwa i Rozwoju Wsi",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-23",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 2182,
            "czesc": "35",
            "czesc_name": null,
            "v_nation": 2182,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-24",
                    "parent_sort": "022-002-024",
                    "idef": "22-2-24-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-024-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "-",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-24-1",
                    "parent_sort": "022-002-024-001",
                    "idef": "22-2-24-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-024-001-001",
                    "elem_name": "Ocena opisowa Kierownictwa",
                    "wartosc_bazowa": "-"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Skarbu Państwa",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-24",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 23123,
            "czesc": "36",
            "czesc_name": null,
            "v_nation": 23123,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-25",
                    "parent_sort": "022-002-025",
                    "idef": "22-2-25-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-025-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "4",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-25-1",
                    "parent_sort": "022-002-025-001",
                    "idef": "22-2-25-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-025-001-001",
                    "elem_name": "Ocena jakości obsługi administracyjnej prezz departamenty merytoryczne",
                    "wartosc_bazowa": "4"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Sprawiedliwości",
            "parent": "22-2",
            "v_eu": 17583,
            "idef": "22-2-25",
            "level": "c",
            "v_proc_nation": 82.91,
            "v_total": 102873,
            "czesc": "37",
            "czesc_name": null,
            "v_nation": 85290,
            "v_proc_eu": 17.09,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-26",
                    "parent_sort": "022-002-026",
                    "idef": "22-2-26-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-026-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "15,0%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-26-1",
                    "parent_sort": "022-002-026-001",
                    "idef": "22-2-26-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-026-001-001",
                    "elem_name": "Wskaźnik fluktuacji kadr",
                    "wartosc_bazowa": "32,17%"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Nauki i Szkolnictwa Wyższego",
            "parent": "22-2",
            "v_eu": 1110,
            "idef": "22-2-26",
            "level": "c",
            "v_proc_nation": 92.97,
            "v_total": 15786,
            "czesc": "38",
            "czesc_name": null,
            "v_nation": 14676,
            "v_proc_eu": 7.03,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-27",
                    "parent_sort": "022-002-027",
                    "idef": "22-2-27-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-027-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "23%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-27-1",
                    "parent_sort": "022-002-027-001",
                    "idef": "22-2-27-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-027-001-001",
                    "elem_name": "Udział pracowników obsługi administracyjnej do ogółu zatrudnionych w %",
                    "wartosc_bazowa": "23%"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Infrastruktury",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-27",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 13371,
            "czesc": "39",
            "czesc_name": null,
            "v_nation": 13371,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-28",
                    "parent_sort": "022-002-028",
                    "idef": "22-2-28-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-028-001",
                    "elem_name": "Coroczne utrzymanie sprawnego funkcjonowania MSiT i sprawnej obsługi pracowników MSiT",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "5",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-28-1",
                    "parent_sort": "022-002-028-001",
                    "idef": "22-2-28-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-028-001-001",
                    "elem_name": "Liczba niesprawności w funkcjonowaniu MSiT i obsłudze pracowników MSiT w danym roku (w szt.)",
                    "wartosc_bazowa": "6"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Sportu i Turystyki",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-28",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 638,
            "czesc": "40",
            "czesc_name": null,
            "v_nation": 638,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-29",
                    "parent_sort": "022-002-029",
                    "idef": "22-2-29-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-029-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "TAK",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-29-1",
                    "parent_sort": "022-002-029-001",
                    "idef": "22-2-29-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-029-001-001",
                    "elem_name": "Wartość logiczna TAK/NIE",
                    "wartosc_bazowa": "TAK"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Środowiska",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-29",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 63985,
            "czesc": "41",
            "czesc_name": null,
            "v_nation": 63985,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-30",
                    "parent_sort": "022-002-030",
                    "idef": "22-2-30-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-030-001",
                    "elem_name": "Zapewnianie sprawnego funkcjonowania Urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "pozytywny wynik audytu wewnętrznego",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-30-1",
                    "parent_sort": "022-002-030-001",
                    "idef": "22-2-30-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-030-001-001",
                    "elem_name": "Ocena efektywności realizacji zadań administracyjnych Ministerstwa SWiA",
                    "wartosc_bazowa": "pozytywny wynik audytu wewnętrznego"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Spraw Wewnętrznych i Administracji",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-30",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 24106,
            "czesc": "42",
            "czesc_name": null,
            "v_nation": 24106,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-31",
                    "parent_sort": "022-002-031",
                    "idef": "22-2-31-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-031-001",
                    "elem_name": "Zapewnianie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "pozytywny wynik audytu wewnętrznego",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-31-1",
                    "parent_sort": "022-002-031-001",
                    "idef": "22-2-31-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-031-001-001",
                    "elem_name": "Ocena efektywności realizacji zadań administracyjnych Ministerstwa SWiA",
                    "wartosc_bazowa": "pozytywny wynik audytu wewnętrznego"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Spraw Wewnętrznych i Administracji",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-31",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 1254,
            "czesc": "43",
            "czesc_name": null,
            "v_nation": 1254,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-32",
                    "parent_sort": "022-002-032",
                    "idef": "22-2-32-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-032-001",
                    "elem_name": "Zapewnianie sprawnego funkcjonowania Urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "-",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-32-1",
                    "parent_sort": "022-002-032-001",
                    "idef": "22-2-32-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-032-001-001",
                    "elem_name": "Wartość środków finansowych przeznaczonych na realizację zadania",
                    "wartosc_bazowa": "-"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Pracy i Polityki Społecznej",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-32",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 4870,
            "czesc": "44",
            "czesc_name": null,
            "v_nation": 4870,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-33",
                    "parent_sort": "022-002-033",
                    "idef": "22-2-33-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-033-001",
                    "elem_name": "Sprawna obsługa administracyjna ministerstwa i placówek zagranicznych",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "dobra",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-33-1",
                    "parent_sort": "022-002-033-001",
                    "idef": "22-2-33-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-033-001-001",
                    "elem_name": "Ocena członków Kierownictwa i dyrektorów komórek organizacyjnych – ankieta wewnętrzna",
                    "wartosc_bazowa": "dobra"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Spraw Zagranicznych",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-33",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 52635,
            "czesc": "45",
            "czesc_name": null,
            "v_nation": 52635,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-34",
                    "parent_sort": "022-002-034",
                    "idef": "22-2-34-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-034-001",
                    "elem_name": "Zapewnianie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "20,97",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-34-1",
                    "parent_sort": "022-002-034-001",
                    "idef": "22-2-34-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-034-001-001",
                    "elem_name": "Liczba pracowników obsługi administracyjnej na 100 pracowników w urzędzie",
                    "wartosc_bazowa": "20,97"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Zdrowia",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-34",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 7807,
            "czesc": "46",
            "czesc_name": null,
            "v_nation": 7807,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-35",
                    "parent_sort": "022-002-035",
                    "idef": "22-2-35-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-035-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania Urzędu i pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "65% ocen pozytywnych",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-35-1",
                    "parent_sort": "022-002-035-001",
                    "idef": "22-2-35-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-035-001-001",
                    "elem_name": "Dostępność do świadczeń w zakresie podnoszenia kwalifikacji i ZFŚS - ocena pracowników(%)",
                    "wartosc_bazowa": "-"
                }
            ],
            "leaf": true,
            "name": "Urząd Zamówień Publicznych",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-35",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 2646,
            "czesc": "49",
            "czesc_name": null,
            "v_nation": 2646,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-36",
                    "parent_sort": "022-002-036",
                    "idef": "22-2-36-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-036-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania Urzędu poprzez sprawną obsługę administracyjną",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "11,3",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-36-1",
                    "parent_sort": "022-002-036-001",
                    "idef": "22-2-36-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-036-001-001",
                    "elem_name": "Udział kosztów obsługi administracyjnej w stosunku do kosztów zadania głównego",
                    "wartosc_bazowa": "11,4"
                }
            ],
            "leaf": true,
            "name": "Urząd Regulacji Energetyki",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-36",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 3680,
            "czesc": "50",
            "czesc_name": null,
            "v_nation": 3680,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-37",
                    "parent_sort": "022-002-037",
                    "idef": "22-2-37-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-037-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania Urzędu w zakresie obsługi administracyjnej przy rozsądnym koszcie operacyjnym",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "18%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-37-1",
                    "parent_sort": "022-002-037-001",
                    "idef": "22-2-37-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-037-001-001",
                    "elem_name": "Wynagrodzenia pracowników obsługi administracyjnej do ogółu wydatków na wynagrodzenia w Urzędzie",
                    "wartosc_bazowa": "17%"
                }
            ],
            "leaf": true,
            "name": "Urząd Ochrony Konkurencji i Konsumentów",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-37",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 8100,
            "czesc": "53",
            "czesc_name": null,
            "v_nation": 8100,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-38",
                    "parent_sort": "022-002-038",
                    "idef": "22-2-38-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-038-001",
                    "elem_name": "Doskonalenie działalności urzędów górniczych w perspektywach: procesów wewnętrznych, doskonalenia i rozwoju oraz finansowej",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "75%",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-38-1",
                    "parent_sort": "022-002-038-001",
                    "idef": "22-2-38-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-038-001-001",
                    "elem_name": "Odsetek osiągniętych progów satysfakcji w ramach celów operacyjnych w perspektywach: procesów wewnętrznych, doskonalenia i rozwoju oraz finansowej",
                    "wartosc_bazowa": "70%"
                }
            ],
            "leaf": true,
            "name": "Wyższy Urząd Górniczy",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-38",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 3051,
            "czesc": "60",
            "czesc_name": null,
            "v_nation": 3051,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-39",
                    "parent_sort": "022-002-039",
                    "idef": "22-2-39-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-039-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "8,74",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-39-1",
                    "parent_sort": "022-002-039-001",
                    "idef": "22-2-39-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-039-001-001",
                    "elem_name": "Odsetek urzędników służby cywilnej w korpusie służby cywilnej w urzędzie (%)",
                    "wartosc_bazowa": "9,20"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Rolnictwa i Rozwoju Wsi",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-39",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 1527,
            "czesc": "62",
            "czesc_name": null,
            "v_nation": 1527,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-40",
                    "parent_sort": "022-002-040",
                    "idef": "22-2-40-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-040-001",
                    "elem_name": "Zapewnianie sprawnego funkcjonowania Urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "-",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-40-1",
                    "parent_sort": "022-002-040-001",
                    "idef": "22-2-40-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-040-001-001",
                    "elem_name": "Wartość środków finansowych przeznaczonych na realizację zadania",
                    "wartosc_bazowa": "-"
                }
            ],
            "leaf": true,
            "name": "Ministerstwo Pracy i Polityki Społecznej",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-40",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 177,
            "czesc": "63",
            "czesc_name": null,
            "v_nation": 177,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-41",
                    "parent_sort": "022-002-041",
                    "idef": "22-2-41-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-041-001",
                    "elem_name": "Zabezpieczenie logistyczne instytucji",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "-",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-41-1",
                    "parent_sort": "022-002-041-001",
                    "idef": "22-2-41-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-041-001-001",
                    "elem_name": "-",
                    "wartosc_bazowa": "-"
                }
            ],
            "leaf": true,
            "name": "Polski Komitet Normalizacyjny",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-41",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 3233,
            "czesc": "65",
            "czesc_name": null,
            "v_nation": 3233,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-42",
                    "parent_sort": "022-002-042",
                    "idef": "22-2-42-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-042-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania Państwowej Agencji Atomistyki i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "28",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-42-1",
                    "parent_sort": "022-002-042-001",
                    "idef": "22-2-42-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-042-001-001",
                    "elem_name": "Liczba pracowników obsługi administracyjnej na 100 pracowników merytorycznych",
                    "wartosc_bazowa": "28"
                }
            ],
            "leaf": true,
            "name": "Państwowa Agencja Atomistyki",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-42",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 2174,
            "czesc": "68",
            "czesc_name": null,
            "v_nation": 2174,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-43",
                    "parent_sort": "022-002-043",
                    "idef": "22-2-43-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-043-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "Wystarczająca",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-43-1",
                    "parent_sort": "022-002-043-001",
                    "idef": "22-2-43-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-043-001-001",
                    "elem_name": "Ocena wewnętrzna audytu",
                    "wartosc_bazowa": "Wystarczająca"
                }
            ],
            "leaf": true,
            "name": "Urząd Transportu Kolejowego",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-43",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 1938,
            "czesc": "71",
            "czesc_name": null,
            "v_nation": 1938,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-44",
                    "parent_sort": "022-002-044",
                    "idef": "22-2-44-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-044-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania Kasy a tym samym terminowej realizacji zadań",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "98,1",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-44-1",
                    "parent_sort": "022-002-044-001",
                    "idef": "22-2-44-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-044-001-001",
                    "elem_name": "Stopień realizacji wydatków Funduszu Administracyjnego",
                    "wartosc_bazowa": "98,1"
                }
            ],
            "leaf": true,
            "name": "Kasa Rolniczego Ubezpieczenia Społecznego",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-44",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 0,
            "czesc": "72",
            "czesc_name": null,
            "v_nation": 0,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-45",
                    "parent_sort": "022-002-045",
                    "idef": "22-2-45-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-045-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "100",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-45-1",
                    "parent_sort": "022-002-045-001",
                    "idef": "22-2-45-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-045-001-001",
                    "elem_name": "Terminowość załatwiania spraw",
                    "wartosc_bazowa": "100"
                }
            ],
            "leaf": true,
            "name": "Urząd Komunikacji Elektronicznej",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-45",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 19734,
            "czesc": "76",
            "czesc_name": null,
            "v_nation": 19734,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": [
                {
                    "wartosc_rok_obec": null,
                    "leaf": false,
                    "elem_type": "Cel",
                    "parent": "22-2-46",
                    "parent_sort": "022-002-046",
                    "idef": "22-2-46-1",
                    "elem_level": "d",
                    "idef_sort": "022-002-046-001",
                    "elem_name": "Zapewnienie sprawnego funkcjonowania urzędu i sprawnej obsługi pracowników",
                    "wartosc_bazowa": null
                },
                {
                    "wartosc_rok_obec": "-",
                    "leaf": true,
                    "elem_type": "Miernik",
                    "parent": "22-2-46-1",
                    "parent_sort": "022-002-046-001",
                    "idef": "22-2-46-1-1",
                    "elem_level": "e",
                    "idef_sort": "022-002-046-001-001",
                    "elem_name": "Stopień zadowolenia pracowników z obsługi administracyjnej (ankieta wśród pracowników - skala do 1 do 5, gdzie: 1 - bardzo niezadowolony, 5 - bardzo zadowolony)",
                    "wartosc_bazowa": "-"
                }
            ],
            "leaf": true,
            "name": "Wojewodowie",
            "parent": "22-2",
            "v_eu": 0,
            "idef": "22-2-46",
            "level": "c",
            "v_proc_nation": 100.0,
            "v_total": 194392,
            "czesc": "85",
            "czesc_name": null,
            "v_nation": 194392,
            "v_proc_eu": 0.0,
            "type": "Dysponent"
        },
        {
            "info": null,
            "leaf": false,
            "name": "Sprawowanie wymiaru sprawiedliwości przez sądy powszechne i wojskowe",
            "parent": "18",
            "v_eu": 0,
            "idef": "18-1",
            "level": "b",
            "v_proc_nation": 100.0,
            "v_total": 5554481,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 5554481,
            "v_proc_eu": 0.0,
            "type": "Zadanie 18.1"
        },
        {
            "info": null,
            "leaf": false,
            "name": "Sprawowanie wymiaru sprawiedliwości przez sądownictwo administracyjne",
            "parent": "18",
            "v_eu": 0,
            "idef": "18-2",
            "level": "b",
            "v_proc_nation": 100.0,
            "v_total": 350494,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 350494,
            "v_proc_eu": 0.0,
            "type": "Zadanie 18.2"
        },
        {
            "info": null,
            "leaf": false,
            "name": "Sprawowanie wymiaru sprawiedliwości przez Sąd Najwyższy oraz działalność KRS",
            "parent": "18",
            "v_eu": 0,
            "idef": "18-3",
            "level": "b",
            "v_proc_nation": 100.0,
            "v_total": 82710,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 82710,
            "v_proc_eu": 0.0,
            "type": "Zadanie 18.3"
        },
        {
            "info": null,
            "leaf": false,
            "name": "Wykonywanie kary pozbawienia wolności i tymczasowego aresztowania",
            "parent": "18",
            "v_eu": 16598,
            "idef": "18-4",
            "level": "b",
            "v_proc_nation": 99.31,
            "v_total": 2393879,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 2377281,
            "v_proc_eu": 0.69,
            "type": "Zadanie 18.4"
        },
        {
            "info": null,
            "leaf": false,
            "name": "Przeciwdziałanie demoralizacji i przestępczości wśród nieletnich i stworzenie warunków do powrotu nieletnich do normalnego życia",
            "parent": "18",
            "v_eu": 4882,
            "idef": "18-5",
            "level": "b",
            "v_proc_nation": 97.7,
            "v_total": 212192,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 207310,
            "v_proc_eu": 2.3,
            "type": "Zadanie 18.5"
        },
        {
            "info": null,
            "leaf": false,
            "name": "Informatyzacja działalności i budowa społeczeństwa informacyjnego",
            "parent": "18",
            "v_eu": 14247,
            "idef": "18-6",
            "level": "b",
            "v_proc_nation": 94.58,
            "v_total": 262676,
            "czesc": null,
            "czesc_name": null,
            "v_nation": 248429,
            "v_proc_eu": 5.42,
            "type": "Zadanie 18.6"
        }
    ];
